/*
Solve the following problem using a program: Suppose you save $100 each month into a savings
account with an annual interest rate of 5%. Thus, the monthly interest rate is 0.05/12 = 0.00417.
After the first month, the value in the account becomes 100 * (1 + 0.00417) = 100.417
After the second month, the value in the account becomes (100 + 100.417) * (1 + 0.00417) =
201.252
And after the third month, the value in the account becomes (100 + 201.252) * (1 + 0.00417) =
302.507
… and so on.
Write a program that randomly generates monthly savings amounts for the 15 runners in Problem 4.
Each monthly saving should be in the range of $100 to $800. Extend the AddressBook class to
store the monthly savings generated by the random number generator.
Then, display the final account value for each of the 15 runners.
 */

public class Question5 {

    private static double PRINCIPLE = 100;

    public static void main(String[] args) {

        EmployeeSavings employeeSavings = new EmployeeSavings("r", "s");


        EmployeeSavings[] es = new EmployeeSavings[]{
                new EmployeeSavings("Elena", "Brandon"),
                new EmployeeSavings("Thomas", "Molson"),
                new EmployeeSavings("Hamilton", "Winn"),
                new EmployeeSavings("Suzie", "Sarandin"),
                new EmployeeSavings("Philip", "Winne"),
                new EmployeeSavings("Alex", "Trebok"),
                new EmployeeSavings("Emma", "Pivoto"),
                new EmployeeSavings("John", "Lenthen"),
                new EmployeeSavings("James", "Lean"),
                new EmployeeSavings("Jane", "Ostin"),
                new EmployeeSavings("Emily", "Car"),
                new EmployeeSavings("Daniel", "Hamshire"),
                new EmployeeSavings("Neda", "Bazdar"),
                new EmployeeSavings("Aaron", "Smith"),
                new EmployeeSavings("Kate", "Hen")};

        String report = EmployeeSavings.getReport(es);
        System.out.println(report);


    }
}