/*
Solve the following problem using a program: Suppose you save $100 each month into a savings
account with an annual interest rate of 5%. Thus, the monthly interest rate is 0.05/12 = 0.00417.
After the first month, the value in the account becomes 100 * (1 + 0.00417) = 100.417
After the second month, the value in the account becomes (100 + 100.417) * (1 + 0.00417) =
201.252
And after the third month, the value in the account becomes (100 + 201.252) * (1 + 0.00417) =
302.507
… and so on.
Write a program that randomly generates monthly savings amounts for the 15 runners in Problem 4.
Each monthly saving should be in the range of $100 to $800. Extend the AddressBook class to
store the monthly savings generated by the random number generator.
Then, display the final account value for each of the 15 runners.
 */

public class Question5 {

    private static double PRINCIPLE = 100;

    public static void main(String[] args) {

        System.out.println("Showing monthly savings");
        EmployeeSavings employeeSavings = new EmployeeSavings("r","s");
        double[] savings = employeeSavings.generateMonthlySavings();
        for (double s : savings ) {
            System.out.println(s);
        }

        System.out.println("Showing accumulated value");
        double[] interests = employeeSavings.calculateInterest();
        for (double i: interests) {
            System.out.println(i);
        }

        System.out.println("Showing monthly interests");
        double[] interestOnly = employeeSavings.getMonthlyInterests();
        for (double i: interestOnly) {
            System.out.println(i);
        }

        System.out.println("account value is: " + employeeSavings.getAccountValue());
    }


}

/*
//        double sum = 100;
//        double previousMonthSum = 0;
//        double count = 0;
//        boolean countReached = false;
//
//        do {
//            sum = (PRINCIPLE + previousMonthSum)*(1 + (0.05/12));
//            System.out.println("previous month:" + previousMonthSum);
//            System.out.println("sum is: " + sum);
//            previousMonthSum = sum;
//            countReached = (count == 2);
//            count++;
//
//        } while (!countReached);
//        System.out.println(sum);
 */